config/routes.rb
Rails.application.routes.draw do
  resources :addresses

  resources :orders do
  	member do
  		get :confirm
  	end
  end

  resources :order_items

  resources :products

  match '/login' => redirect("/auth/twitter"), as: :login, via: :get
  match 'auth/:provider/callback', to: 'sessions#create', via: :get
  match "/logout" => 'sessions#destroy', as: :logout, via: :get

  root 'products#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  has_many :order_items, dependent: :destroy

  def total
  	total = 0
  	order_items.each do |item|
  		total += item.subtotal
  	end
  	total
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :confirm]

  def confirm
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params.merge(status: "submitted"))
        session[:order_id] = nil
        format.html { redirect_to confirm_order_path(@order), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :status, :address_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.user.name if @order.user %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
    <th>Stock Status</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
    <th></th>
  </tr>
	<% @order.order_items.each do |order_item| %>
  <tr>
  	<td><%= image_tag order_item.product.image_url, height: '150px' %></td>
  	<td><%= order_item.product.title %></td>
  	<td><%= link_to "#{order_item.quantity} (edit)", edit_order_item_path(order_item) %></td>
    <td><%= print_stock(order_item.product.stock, order_item.quantity) %></td>
  	<td><%= order_item.product.price %></td>
  	<td><%= order_item.subtotal %></td>
  	<td><%= link_to "Remove", order_item_path(order_item), method: :delete, class: 'btn btn-danger' %></td>
  </tr>
	<% end %> 
	<tr>
		<td colspan="3"></td>
		<td>Total</td>
		<td><%= @order.total %></td>
	</tr>
  <tr>
    <%= form_for(@order) do |f| %>
      Shipping To: 
      <%= f.select :address_id, options_for_select(current_user.addresses.collect{|a| [a.line1, a.id]}) %>
      <%= f.submit "Checkout" %>
    <% end %>
  </tr> 
  &nbsp;<%= link_to "Add New Address", new_address_path, class: "btn btn-primary" %>
</table>
<br />
<%= link_to "Empty Cart", order_path(@order), class: 'btn btn-primary', method: :delete %>