config/routes.rb
Rails.application.routes.draw do
  resources :addresses

  resources :orders do
  	member do
  		get :confirm
  	end
  end

  resources :order_items

  resources :products

  match '/login' => redirect("/auth/twitter"), as: :login, via: :get
  match 'auth/:provider/callback', to: 'sessions#create', via: :get
  match "/logout" => 'sessions#destroy', as: :logout, via: :get

  root 'products#index'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  price       :decimal(8, 2)
#  description :text
#  image_url   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  stock       :integer          default("0")
#

class Product < ActiveRecord::Base
	has_many :order_items
	mount_uploader :image_url, ImageUploader
	validates_numericality_of :price
	validates :stock, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :image_url, :stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def print_price(price)
		# format("INR %.2f", price)
		number_to_currency price
	end

	def print_stock(stock, requested=1)
		if stock <=0
			return "Out of Stock"
		elsif stock < requested
			return content_tag(:span, "Insufficient Stock (#{stock})", class: 'low_stock')
		elsif stock > requested
			return content_tag(:span, stock, class: 'in_stock')
		end
	end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price, 'Price (like 2.99)' %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.file_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :stock %>
    <%= f.text_field :stock %>
  </div><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Products</h1>

<table>
  <thead>
    <tr>
      <th>Image url</th>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th>Stock</th>
      <th>Add to Cart</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= image_tag product.image_url, style: 'height: 150px;' %></td>
      <td><span class="product_title"><%= link_to product.title, product_path(product) %></span><%= product.description %></td>
      <td><%= print_price(product.price) %></td>
      <td></td>
      <td><%= print_stock(product.stock) %></td>
      <td><%= button_to "Add to Cart", order_items_path(product_id: product.id), class: 'btn btn-default' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a New Product', new_product_path, id: "new_product" %>

app/views/products/new.html.erb
<h1>Create a New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>